


version: "3.8"

services:
  api:
    image: "oauth2_api"
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./auth_api:/code 
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
